spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/shop_electronic
    username: admin
    password: admin
  flyway:
    baseline-on-migrate: true
server:
  port: 8012
file:
  upload-dir: uploads
